### ISSUE TITLE
CI failures: 20190110 - 20190116

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/reliability#20]
Failures in [node-test-pull-request/20055](https://ci.nodejs.org/job/node-test-pull-request/20055/) to [node-test-pull-request/20153](https://ci.nodejs.org/job/node-test-pull-request/20153/) that failed more than 2 PRs
(Generated with `ncu-ci walk pr --stats --copy`)

### JSTest Failure

| Reason | <code>known_issues/test-vm-timeout-escape-queuemicrotask</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 25 (https://github.com/nodejs/node/pull/25441/, https://github.com/nodejs/node/pull/24951/, https://github.com/nodejs/node/pull/25463/, https://github.com/nodejs/node/pull/22712/, https://github.com/nodejs/node/pull/25466/, https://github.com/nodejs/node/pull/25480/, https://github.com/nodejs/node/pull/25430/, https://github.com/nodejs/node/pull/25488/, https://github.com/nodejs/node/pull/25415/, https://github.com/nodejs/node/pull/25479/, https://github.com/nodejs/node/pull/25364/, https://github.com/nodejs/node/pull/25412/, https://github.com/nodejs/node/pull/25472/, https://github.com/nodejs/node/pull/25490/, https://github.com/nodejs/node/pull/25443/, https://github.com/nodejs/node/pull/25502/, https://github.com/nodejs/node/pull/25481/, https://github.com/nodejs/node/pull/25381/, https://github.com/nodejs/node/pull/25429/, https://github.com/nodejs/node/pull/25008/, https://github.com/nodejs/node/pull/24819/, https://github.com/nodejs/node/pull/25507/, https://github.com/nodejs/node/pull/25508/, https://github.com/nodejs/node/pull/25473/, https://github.com/nodejs/node/pull/25455/) |
| Appeared | [test-packetnet-centos7-arm64-1](https://ci.nodejs.org/computer/test-packetnet-centos7-arm64-1/), [test-packetnet-ubuntu1604-arm64-2](https://ci.nodejs.org/computer/test-packetnet-ubuntu1604-arm64-2/), [test-packetnet-ubuntu1604-arm64-1](https://ci.nodejs.org/computer/test-packetnet-ubuntu1604-arm64-1/), [test-joyent-smartos17-x64-2](https://ci.nodejs.org/computer/test-joyent-smartos17-x64-2/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20074/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20137/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=centos7-arm64-gcc6/21454/console">Example</a></summary>

```
not ok 2345 known_issues/test-vm-timeout-escape-queuemicrotask
  ---
  duration_ms: 0.333
  severity: fail
  stack: |-
    (node:38468) ExperimentalWarning: queueMicrotask() is experimental.
  ...

```
</details>

-------

| Reason | <code>parallel/test-trace-events-fs-sync</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 15 (https://github.com/nodejs/node/pull/25412/, https://github.com/nodejs/node/pull/25447/, https://github.com/nodejs/node/pull/25441/, https://github.com/nodejs/node/pull/25429/, https://github.com/nodejs/node/pull/25443/, https://github.com/nodejs/node/pull/25480/, https://github.com/nodejs/node/pull/22712/, https://github.com/nodejs/node/pull/25415/, https://github.com/nodejs/node/pull/25364/, https://github.com/nodejs/node/pull/25481/, https://github.com/nodejs/node/pull/25084/, https://github.com/nodejs/node/pull/25503/, https://github.com/nodejs/node/pull/25473/, https://github.com/nodejs/node/pull/25455/, https://github.com/nodejs/node/pull/23100/) |
| Appeared | [test-azure_msft-win10-x64-3](https://ci.nodejs.org/computer/test-azure_msft-win10-x64-3/), [test-azure_msft-win10-x64-2](https://ci.nodejs.org/computer/test-azure_msft-win10-x64-2/), [test-azure_msft-win10-x64-4](https://ci.nodejs.org/computer/test-azure_msft-win10-x64-4/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20058/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20142/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows/COMPILED_BY=vs2017,RUNNER=win10,RUN_SUBSET=0/23098/console">Example</a></summary>

```
not ok 494 parallel/test-trace-events-fs-sync
  ---
  duration_ms: 0.794
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows\test\parallel\test-trace-events-fs-sync.js:140
        throw new Error(`${tr}:\n${util.inspect(proc)}`);
        ^
    
    Error: fs.sync.fchmod:
    { status: 3221225477,
      signal: null,
      output: [ null, '', '' ],
      pid: 1756,
      stdout: '',
      stderr: '' }
        at Object.<anonymous> (c:\workspace\node-test-binary-windows\test\parallel\test-trace-events-fs-sync.js:140:11)
        at Module._compile (internal/modules/cjs/loader.js:722:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
        at Module.load (internal/modules/cjs/loader.js:621:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:564:12)
        at Function.Module._load (internal/modules/cjs/loader.js:556:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
        at executeUserCode (internal/bootstr...
```
</details>

-------

| Reason | <code>parallel/test-tls-cli-min-version-1.1</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 (https://github.com/nodejs/node/pull/25447/, https://github.com/nodejs/node/pull/25381/) |
| Appeared | [test-digitalocean-ubuntu1604_sharedlibs_container-x64-6](https://ci.nodejs.org/computer/test-digitalocean-ubuntu1604_sharedlibs_container-x64-6/), [test-osuosl-aix61-ppc64_be-2](https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-2/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20062/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20067/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_openssl110_x64/9954/console">Example</a></summary>

```
not ok 1837 parallel/test-tls-cli-min-version-1.1
  ---
  duration_ms: 0.413
  severity: fail
  exitcode: 1
  stack: |-
    test: U U U U U SSLv2_method expect U U ERR_TLS_INVALID_PROTOCOL_METHOD
    client undefined
    server ERR_TLS_INVALID_PROTOCOL_METHOD
    test: U U U U U SSLv3_method expect U U ERR_TLS_INVALID_PROTOCOL_METHOD
    client undefined
    server ERR_TLS_INVALID_PROTOCOL_METHOD
    test: U U U U U hokey-pokey expect U U ERR_TLS_INVALID_PROTOCOL_METHOD
    client undefined
    server ERR_TLS_INVALID_PROTOCOL_METHOD
    test: U U U U TLSv1.2 TLS1_2_method expect U U ERR_TLS_PROTOCOL_VERSION_CONFLICT
    client undefined
    server ERR_TLS_PROTOCOL_VERSION_CONFLICT
    test: U U U TLSv1.2 U TLS1_2_method expect U U ERR_TLS_PROTOCOL_VERSION_CONFLICT
    client undefined
    server ERR_TLS_PROTOCOL_VERSION_CONFLICT
    test: U U SSLv2_method U U U expect U ERR_TLS_INVALID_PROTOCOL_METHOD U
    client ERR_TLS_INVALID_PROTOCOL_METHOD
    server undefined
    test: U U SSLv3_method U U U expect U E...
```
</details>

-------

| Reason | <code>parallel/test-tls-min-max-version</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 (https://github.com/nodejs/node/pull/25447/, https://github.com/nodejs/node/pull/25381/) |
| Appeared | [test-digitalocean-ubuntu1604_sharedlibs_container-x64-6](https://ci.nodejs.org/computer/test-digitalocean-ubuntu1604_sharedlibs_container-x64-6/), [test-osuosl-aix61-ppc64_be-2](https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-2/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20062/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20067/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_openssl110_x64/9954/console">Example</a></summary>

```
not ok 1899 parallel/test-tls-min-max-version
  ---
  duration_ms: 0.360
  severity: fail
  exitcode: 1
  stack: |-
    test: U U U U U SSLv2_method expect U U ERR_TLS_INVALID_PROTOCOL_METHOD
    client undefined
    server ERR_TLS_INVALID_PROTOCOL_METHOD
    test: U U U U U SSLv3_method expect U U ERR_TLS_INVALID_PROTOCOL_METHOD
    client undefined
    server ERR_TLS_INVALID_PROTOCOL_METHOD
    test: U U U U U hokey-pokey expect U U ERR_TLS_INVALID_PROTOCOL_METHOD
    client undefined
    server ERR_TLS_INVALID_PROTOCOL_METHOD
    test: U U U U TLSv1.2 TLS1_2_method expect U U ERR_TLS_PROTOCOL_VERSION_CONFLICT
    client undefined
    server ERR_TLS_PROTOCOL_VERSION_CONFLICT
    test: U U U TLSv1.2 U TLS1_2_method expect U U ERR_TLS_PROTOCOL_VERSION_CONFLICT
    client undefined
    server ERR_TLS_PROTOCOL_VERSION_CONFLICT
    test: U U SSLv2_method U U U expect U ERR_TLS_INVALID_PROTOCOL_METHOD U
    client ERR_TLS_INVALID_PROTOCOL_METHOD
    server undefined
    test: U U SSLv3_method U U U expect U ERR_T...
```
</details>

-------

| Reason | <code>parallel/test-worker-exit-code</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 (https://github.com/nodejs/node/pull/25381/, https://github.com/nodejs/node/pull/25472/) |
| Appeared | [test-rackspace-win2008r2-x64-3](https://ci.nodejs.org/computer/test-rackspace-win2008r2-x64-3/), [test-rackspace-win2008r2-x64-6](https://ci.nodejs.org/computer/test-rackspace-win2008r2-x64-6/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20067/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20115/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows/COMPILED_BY=vs2017,RUNNER=win2008r2-vs2017,RUN_SUBSET=2/23062/console">Example</a></summary>

```
not ok 532 parallel/test-worker-exit-code
  ---
  duration_ms: 0.501
  severity: fail
  exitcode: 1
  stack: |-
    ok - 0 exited with 42
    ok - 1 exited with 42
    ok - 2 exited with 0
    Error: ok
        at Object.exitWithOneOnUncaught [as func] (c:\workspace\node-test-binary-windows\test\fixtures\process-exit-code-cases.js:47:9)
        at MessagePort.parentPort.once (c:\workspace\node-test-binary-windows\test\parallel\test-worker-exit-code.js:23:54)
        at Object.onceWrapper (events.js:276:13)
        at MessagePort.emit (events.js:188:13)
        at MessagePort.onmessage (internal/worker/io.js:68:8)
    ok - 3 exited with 1
    ok - 5 exited with 0
    ok - 4 exited with 99
    ok - 6 exited with 97
    Error: ok
        at Object.exitWithZeroInExitWithUncaught [as func] (c:\workspace\node-test-binary-windows\test\fixtures\process-exit-code-cases.js:107:9)
        at MessagePort.parentPort.once (c:\workspace\node-test-binary-windows\test\parallel\test-worker-exit-code.js:23:54)
        at Object...
```
</details>

-------

| Reason | <code>sequential/test-https-server-keep-alive-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 (https://github.com/nodejs/node/pull/25479/, https://github.com/nodejs/node/pull/25521/) |
| Appeared | [test-digitalocean-freebsd10-x64-1](https://ci.nodejs.org/computer/test-digitalocean-freebsd10-x64-1/), [test-requireio_bengl-debian9-armv6l_pi1p-1](https://ci.nodejs.org/computer/test-requireio_bengl-debian9-armv6l_pi1p-1/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20109/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20146/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd10-64/23411/console">Example</a></summary>

```
not ok 2134 sequential/test-https-server-keep-alive-timeout
  ---
  duration_ms: 2.392
  severity: fail
  exitcode: 1
  stack: |-
    Mismatched noop function calls. Expected exactly 3, actual 1.
        at Object.exports.mustCall (/usr/home/iojs/build/workspace/node-test-commit-freebsd/nodes/freebsd10-64/test/common/index.js:439:10)
        at serverNoEndKeepAliveTimeoutWithPipeline (/usr/home/iojs/build/workspace/node-test-commit-freebsd/nodes/freebsd10-64/test/sequential/test-https-server-keep-alive-timeout.js:59:59)
        at run (/usr/home/iojs/build/workspace/node-test-commit-freebsd/nodes/freebsd10-64/test/sequential/test-https-server-keep-alive-timeout.js:28:11)
        at Server.server.setTimeout.common.mustCall (/usr/home/iojs/build/workspace/node-test-commit-freebsd/nodes/freebsd10-64/test/sequential/test-https-server-keep-alive-timeout.js:41:5)
        at Server.<anonymous> (/usr/home/iojs/build/workspace/node-test-commit-freebsd/nodes/freebsd10-64/test/common/index.js:479:15)
        at emitOne ...
```
</details>

-------

### Jenkins Failure

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 (https://github.com/nodejs/node/pull/25415/, https://github.com/nodejs/node/pull/20803/) |
| Appeared | [test-softlayer-alpine38_container-x64-1](https://ci.nodejs.org/computer/test-softlayer-alpine38_container-x64-1/), [test-softlayer-ubuntu1604_sharedlibs_container-x64-3](https://ci.nodejs.org/computer/test-softlayer-ubuntu1604_sharedlibs_container-x64-3/), [test-rackspace-win2008r2-x64-4](https://ci.nodejs.org/computer/test-rackspace-win2008r2-x64-4/), [test-rackspace-win2012r2-x64-4](https://ci.nodejs.org/computer/test-rackspace-win2012r2-x64-4/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20105/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20143/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/24674/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 32.42.c682.ip4.static.sl-reverse.com/130.198.66.50:36068' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:214)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
	at com.sun.proxy.$Proxy83.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1144)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1136)
```
</details>

-------

### Build Failure

| Reason | <code>ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 (https://github.com/nodejs/node/pull/25412/, https://github.com/nodejs/node/pull/21573/, https://github.com/nodejs/node/pull/25500/, https://github.com/nodejs/node/pull/25501/, https://github.com/nodejs/node/pull/25346/) |
| Appeared | [test-digitalocean-freebsd10-x64-1](https://ci.nodejs.org/computer/test-digitalocean-freebsd10-x64-1/), [test-packetnet-centos7-arm64-1](https://ci.nodejs.org/computer/test-packetnet-centos7-arm64-1/), [test-scaleway-ubuntu1604-armv7l-3](https://ci.nodejs.org/computer/test-scaleway-ubuntu1604-armv7l-3/), [test-packetnet-ubuntu1604-arm64-2](https://ci.nodejs.org/computer/test-packetnet-ubuntu1604-arm64-2/), [test-linuxonecc-rhel72-s390x-1](https://ci.nodejs.org/computer/test-linuxonecc-rhel72-s390x-1/), [test-requireio_indieisaconcept-debian9-armv6l_pi1p-1](https://ci.nodejs.org/computer/test-requireio_indieisaconcept-debian9-armv6l_pi1p-1/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20058/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20145/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd10-64/23410/console">Example</a></summary>

```
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>Error: [Errno 13] Permission denied: 'c:\\workspace\\node-compile-windows\\Release\\obj\\global_intermediate\\src\\inspector\\injected-script-source.h'</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 (https://github.com/nodejs/node/pull/25439/, https://github.com/nodejs/node/pull/25488/, https://github.com/nodejs/node/pull/23834/) |
| Appeared | [test-rackspace-win2012r2-x64-11](https://ci.nodejs.org/computer/test-rackspace-win2012r2-x64-11/), [test-rackspace-win2012r2-x64-10](https://ci.nodejs.org/computer/test-rackspace-win2012r2-x64-10/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20066/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20144/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-compile-windows/label=win-vs2017-x86/23763/console">Example</a></summary>

```
Error: [Errno 13] Permission denied: 'c:\\workspace\\node-compile-windows\\Release\\obj\\global_intermediate\\src\\inspector\\injected-script-source.h'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [c:\workspace\node-compile-windows\deps\v8\gypfiles\v8_base_3.vcxproj]
  v8-runtime-agent-impl.cc
  v8-stack-trace-impl.cc
  wasm-translation.cc
  address-map.cc
```
</details>

-------

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 (https://github.com/nodejs/node/pull/inspector-console/, https://github.com/nodejs/ecma-script-modules/pull/25/) |
| Appeared | [test-softlayer-ubuntu1604-x64-1](https://ci.nodejs.org/computer/test-softlayer-ubuntu1604-x64-1/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/20057/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/20089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/20089/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

**Comment by joyeecheung** [comment]
### Progress

- `known_issues/test-vm-timeout-escape-queuemicrotask` (25)
- `parallel/test-trace-events-fs-sync` (15)
- `parallel/test-tls-cli-min-version-1.1` (2)
- `parallel/test-tls-min-max-version` (2)
- `parallel/test-worker-exit-code` (2)
- `sequential/test-https-server-keep-alive-timeout` (2)
- `Backing channel 'JNLP4-connect connection from ... is disconnected.` (2)
- `ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?` (5)
- `Error: [Errno 13] Permission denied: 'c:\\workspace\\node-compile-windows\\Release\\obj\\global_intermediate\\src\\inspector\\injected-script-source.h'` (3)
- `Failed to trigger node-test-commit` (2)
