### ISSUE TITLE
create-report Action failing

### ISSUE THREAD

**Issue by mmarchini** [nodejs/reliability#26]
`create-report` Action is still failing after adding secrets to the repository:

```
Run ncu-ci walk pr --stats=true --markdown $PWD/results.md
  ncu-ci walk pr --stats=true --markdown $PWD/results.md
  shell: /bin/bash -e {0}
- Querying https://ci.nodejs.org/job/node-test-pull-request/api/json?tree=builds%5Burl%2Cresult%5D
TypeError: Cannot read property 'filter' of undefined
    at filterBuild (/opt/hostedtoolcache/node/12.18.2/x64/lib/node_modules/node-core-utils/lib/ci/ci_result_parser.js:898:6)
    at listBuilds (/opt/hostedtoolcache/node/12.18.2/x64/lib/node_modules/node-core-utils/lib/ci/ci_result_parser.js:912:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WalkCommand.initialize (/opt/hostedtoolcache/node/12.18.2/x64/lib/node_modules/node-core-utils/bin/ncu-ci:290:20)
    at async main (/opt/hostedtoolcache/node/12.18.2/x64/lib/node_modules/node-core-utils/bin/ncu-ci:391:3)
##[error]Process completed with exit code 1.
```

https://github.com/nodejs/reliability/runs/910446091?check_suite_focus=true

The command works when I run it locally with my credentials, but not with github-bot credentials. I think it the bot access to Jenkins is too restrictive.

**Comment by mmarchini** [comment]
Opened https://github.com/nodejs/build/issues/2394 to deal with lack of permissions on github-bot

**Comment by mmarchini** [comment]
tada
