### ISSUE TITLE
No more CI Reliability report since 4 days ago

### ISSUE THREAD

**Issue by F3n67u** [nodejs/reliability#316]
The last CI Reliability report is 06-29, 4 days ago. 06-30, 07-01, 07-02 is absent. 

@richardlau could you help to take a look?

**Comment by targos** [comment]
End of the logs from https://github.com/nodejs/reliability/runs/7165313876?check_suite_focus=true:

````
2022-07-03T00:18:30.2074274Z --------------------------------- Other builds ---------------------------------
2022-07-03T00:18:30.2074823Z Unstable   https://ci.nodejs.org/job/node-test-commit-osx/45875/
2022-07-03T00:18:30.2075370Z --------------------------------------------------------------------------------
2022-07-03T00:18:30.2075912Z [87/89] Running https://ci.nodejs.org/job/node-test-pull-request/44957/
2022-07-03T00:18:30.2076461Z --------------------------------------------------------------------------------
2022-07-03T00:18:30.2076950Z - Querying data for job/node-test-pull-request/44957/
2022-07-03T00:18:30.4374583Z ✔  Build data downloaded
2022-07-03T00:18:30.4375090Z - Querying failures of job/node-test-commit/54550/
2022-07-03T00:18:31.1725844Z TypeError: Cannot read properties of null (reading '1')
2022-07-03T00:18:31.1726616Z     at new JSTestFailure (file:///opt/hostedtoolcache/node/16.15.1/x64/lib/node_modules/node-core-utils/lib/ci/ci_failure_parser.js:78:62)
2022-07-03T00:18:31.1727317Z     at file:///opt/hostedtoolcache/node/16.15.1/x64/lib/node_modules/node-core-utils/lib/ci/ci_failure_parser.js:168:16
2022-07-03T00:18:31.1727703Z     at Array.map (<anonymous>)
2022-07-03T00:18:31.1728280Z     at filter (file:///opt/hostedtoolcache/node/16.15.1/x64/lib/node_modules/node-core-utils/lib/ci/ci_failure_parser.js:167:29)
2022-07-03T00:18:31.1729023Z     at CIFailureParser.parse (file:///opt/hostedtoolcache/node/16.15.1/x64/lib/node_modules/node-core-utils/lib/ci/ci_failure_parser.js:296:22)
2022-07-03T00:18:31.1729775Z     at TestRun.parseConsoleText (file:///opt/hostedtoolcache/node/16.15.1/x64/lib/node_modules/node-core-utils/lib/ci/build-types/job.js:93:26)
2022-07-03T00:18:31.1730507Z     at runMicrotasks (<anonymous>)
2022-07-03T00:18:31.1730971Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-07-03T00:18:31.1731319Z     at async Promise.all (index 13)
2022-07-03T00:18:31.1732021Z     at async CommitBuild.getResults (file:///opt/hostedtoolcache/node/16.15.1/x64/lib/node_modules/node-core-utils/lib/ci/build-types/commit_build.js:106:25)
2022-07-03T00:18:31.1841036Z ##[error]Process completed with exit code 1.
````

**Comment by richardlau** [comment]
The workflow runs [`ncu-ci pr walk pr`](https://github.com/nodejs/node-core-utils/blob/main/docs/ncu-ci.md#ncu-ci-walk-type), which looks at the 100 most recent `node-test-pull-request` CI runs
https://github.com/nodejs/reliability/blob/506849d9032f01b28f9b9951fc9f397c3d401c3f/.github/workflows/reliability_report.yml#L21-L25
(See https://github.com/nodejs/node-core-utils#setting-up-jenkins-credentials if you want to try running `ncu-ci` yourself.)

From the quoted log it would appear that node-core-utils was unable to parse one of the sub-jobs of job/node-test-commit/54550/ -- presumably the workflow starting working again once enough new CI runs happened to push that job outside the most recent 100.

**Comment by F3n67u** [comment]
> The workflow runs [`ncu-ci pr walk pr`](https://github.com/nodejs/node-core-utils/blob/main/docs/ncu-ci.md#ncu-ci-walk-type), which looks at the 100 most recent `node-test-pull-request` CI runs
> 
> https://github.com/nodejs/reliability/blob/506849d9032f01b28f9b9951fc9f397c3d401c3f/.github/workflows/reliability_report.yml#L21-L25
> 
> 
> (See https://github.com/nodejs/node-core-utils#setting-up-jenkins-credentials if you want to try running `ncu-ci` yourself.)
> From the quoted log it would appear that node-core-utils was unable to parse one of the sub-jobs of job/node-test-commit/54550/ -- presumably the workflow starting working again once enough new CI runs happened to push that job outside the most recent 100.

I don't know that before. Thanks for your info. I thought only collaborators could have Jenkins credentials. I am wrong.

**Comment by F3n67u** [comment]
I could reproduce this problem now. I create a issue at nodejs/node-core-utils. so I close this issue in favor of https://github.com/nodejs/node-core-utils/issues/639.
